[package]
name = "oryx"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oryx"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.8.4"
anyhow = "1.0"
